[package]
name = "simple_room"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
livekit = { path = "../.." }
futures = "0.3"
